### PR TITLE
Individual site config file

### PR DESCRIPTION
**Pull request by tveronezi**
This is the same as https://github.com/eclipse/microprofile-config/pull/171 but with the Signed-off-by in the commits.

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
From your description, the file is optional if I don't care about the order. Right? If so, which order it will use to construct the content. Please confirm.

**Comment by tveronezi** [comment]
@Emily-Jiang this file is not required. It can be used by a project to add custom configuration like a friendly name or a list of documents hosted in the project itself. This PR creates the list of documents like the screenshot bellow...

screen shot 2017-06-16 at 12 03 24 pm

The order of the documents in that list is the order of the documents in this site.yaml file.

Currently, the live version of this project documentation looks like this...



https://microprofile.io/project/eclipse/microprofile-config

**Comment by dblevins** [comment]
Without this file there will be no documentation listed in the right.

**Comment by Emily-Jiang** [comment]
Thanks @tveronezi @dblevins for the explanation! Just try to understand the usage.

**Pull request merged**
