### PR TITLE
#440 exlude EL transitive dependency

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by kenfinnigan** [comment]
I think the exclusion needs to be done in the `dependencyManagement` of the root `pom.xml` as the dependency is also used in the TCK as well

**Comment by Emily-Jiang** [comment]
@kenfinnigan thanks for the info! I thought we only want to exclude from API initially. I have now excluded from the parent.

**Comment by kenfinnigan** [comment]
Unrelated to your change, I just noticed that https://github.com/eclipse/microprofile-config/blob/master/tck/pom.xml#L60 defines the version for the dependency so I think that means it doesn't pick up the dependencyManagement version.

Should the version be removed so it uses the one in the root pom?

**Comment by Emily-Jiang** [comment]
@kenfinnigan I think it will get picked up as the version matches. However, to prevent from future changes that make the versions out of sync, I will remove the version from tck.

**Pull request merged**
