### PR TITLE
Fix broken Converters links in spec

### LINKED ISSUE #637: Multiple broken Converters links in spec
**Description**

There are 3 broken links in the `Accessing or Creating a certain Configuration` part of the spec to the `converters` section of the spec: https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#configprovider

Where `<<converters,Converters>>` should be `<<converter,Converters>>`

### PR DESCRIPTION
**Pull request by Joseph-Cass**
Fixes #637

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by radcortez** [comment]
I believe the correct fix should be here: https://github.com/eclipse/microprofile-config/blob/c2b1197df83ae64d54464473820595a08a970b5a/spec/src/main/asciidoc/converters.asciidoc#L24

**Comment by Joseph-Cass** [comment]
> microprofile-config/spec/src/main/asciidoc/converters.asciidoc

If the link text is changed to `converters`, then note that there are already a couple of links to `converter` which will also need changing in:

- https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/architecture.asciidoc
- https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configprovider.asciidoc (further down, before this PR)

**Comment by radcortez** [comment]
Yes, please. Go ahead.

**Comment by Joseph-Cass** [comment]
> Yes, please. Go ahead.

I've implemented the alternative suggested fix here: https://github.com/eclipse/microprofile-config/pull/640

**Comment by radcortez** [comment]
Thank you!

**Pull request closed without merging**
