### PR TITLE
Correct typos in Config.java

### PR DESCRIPTION
**Pull request by Joseph-Cass**
I made these changes from the Git editor so i'm not sure if i'm merging to/from the correct branch.

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Review by Emily-Jiang — APPROVED** [review]
LGTM! Thanks @Joseph-Cass !

**Comment by Emily-Jiang** [comment]
@Joseph-Cass you need to do `mvn verify` and then check in the formatted changes. At the moment, it failed format validation.

**Comment by Emily-Jiang** [comment]
@genie-microprofile please build

**Pull request merged**
