### PR TITLE
#41 Add default value in the ConfigProperty

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
I'm going to merge this in and discuss one extra API I added getRefreshDuration this afternoon. The PR contains default value capability on the injection model.

**Comment by struberg** [comment]
+1 for the default value in ConfigProperty
-1 for the getRefreshDuration. As explained in the PR (open review question) it is not clear what use case it does solve.

**Comment by struberg** [comment]
Sorry Emily, Both @OndrejM  and I expressed a strong -1 against getRefreshDuration during our yesterdays meeting. And there was also an open Review comment asking for the use case from 15h ago. Let's discuss this in our hangout today.

**Comment by Emily-Jiang** [comment]
That is what I explained in the above comment to discuss this afternoon. I'll detail the use cases in the hangout.

**Comment by OndrejM** [comment]
I don't like doing more than 2 different things in a PR. While I agree with kavadoc changes, the refresh duration discussion has not been closed yet.

**Comment by OndrejM** [comment]
While having a new default method shouldn't hurt, this one is very confusing. The javadoc explains the case of static source, but what should be returned in case of a dynamic one? It's not possible to guess how long a refresh would take. Wouldn't be enough to return just true/false for static/dynamic source? I don't see any point in guessing how fast would the source refresh...

**Comment by Emily-Jiang** [comment]
@OndrejM I think the compromise would be isDynamic to at least state it is dynamic or not. Anyway, I am trying to draft out a note and ask for a wide discussion.

**Comment by struberg** [comment]
Yes, the current method makes not much sense to me for now.
- There is no described use case
- It's nowhere referenced in any test
- It's nowhere implemented

Hard to tell what the intent is actually.

**Pull request merged**
