### PR TITLE
#139 not spec the limitation as it can be achievable

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by struberg** [comment]
Just to explain why the original decision was made: In DeltaSpike we allow to 'erase' configured values in a higher ordinal by overwriting it with an empty value.

For this mechanism to work it makes sense to interpret an empty String as 'not existing value'.

We can now discuss whether it makes sense for MP-config to do the same or not. But removing this feature would be a design change we need to discuss.
So yes, it's not a bug, it's a feature right now!

**Comment by Emily-Jiang** [comment]
For your scenario, if the empty string is treated as non-existing property, how could you erase the property? Basically, if the empty string is only in sourceA, the property does not exist. If the empty string is in sourceA with a higher priority, it erases the config property defined in other config sources with a lower priority. This sounds hacking.

On the other hand, I would like to come up with a better design for the property erasing. Depending on the value is not good. I would recommend to introduce a property naming convention such as $aa$ is for erasing the property aa. You can raise an issue to discuss the requirement.

We have already discussed on the issue 139. Both Ondrej and I agreed we should not spec the limitation. I would like to get this sorted asap.

**Comment by struberg** [comment]
in properties file (ordinal=100): myapp.somekey=bla
in environment (higher ordinal): myapp.somekey=
(empty)

From an appliation pov that hat would be the same like not having myapp.somekey defined in any ConfigSource at all.

**Comment by Emily-Jiang** [comment]
@struberg with what you suggested, we no longer support the config property having a null value as a valid property. e.g. myapp.somekey=
(empty)

**Comment by Emily-Jiang** [comment]
I recommend you raise a separate issue to cover the property deletion. As my explanation earlier, relying on the empty value is not the ideal solution for this.

**Comment by Emily-Jiang** [comment]
@struberg updated the javadoc based on your comments! Thanks!

**Comment by Emily-Jiang** [comment]
Done the javadoc improvement based on your suggestion, Mark. If you have any further comments, please open a separate issue for further tidyup.

**Pull request merged**
