### PR TITLE
[#394] Fix ordinal values in Javadoc

### PR DESCRIPTION
**Pull request by jmesnil**
This fixes https://github.com/eclipse/microprofile-config/issues/394

Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@jmesnil the change is good. Please fix your ECA so that the change can be merged.

**Comment by jmesnil** [comment]
@Emily-Jiang my ECA is correct (it can be confirmed with the ECA validation tool at https://accounts.eclipse.org/legal/eca/validation/10576 with my email address jmesnil@redhat.com) but the bot still complains about it

**Comment by dmlloyd** [comment]
Any update on this @Emily-Jiang?

**Comment by Emily-Jiang** [comment]
Even though the error still shows up, I know @jmesnil has the sign off. I'm going to merge this PR.

**Pull request merged**
