### PR TITLE
#404 Add some info regarding passivation capable injection point

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@rdebusscher can you check to see whether you are happy with the PR?

**Comment by rdebusscher** [comment]
@Emily-Jiang  Seems that I made a comment on the issue and not here https://github.com/eclipse/microprofile-config/issues/404#issuecomment-558336454

Will the TCK update be in a separate PR or in this one?

The text update itself is sufficient for me.

**Comment by Emily-Jiang** [comment]
@rdebusscher as per my explanation, Config does not change any mandated behaviour from CDI. The behaviour you observed is purely CDI. I don't think we should add tests here to test CDI. Adding the sentence is just to provide some pointer to the corresponding section in CDI.

**Comment by rdebusscher** [comment]
@Emily-Jiang I understand it is CDi related, but not all implementations behave properly (not checked anymore since I opened the issue). If we do not enforce it through some TCK test, there might be maybe a difference in behaviour forever.

**Comment by Emily-Jiang** [comment]
Which container did you check? As per my comments earlier, all container with CDI complianced should behave the same. The reason I don't think we need to add tests is that Config did not play any part in this game. It is only to do with `@Inject`.

**Pull request merged**
