### PR TITLE
Minor clarification on ordinal precedence.

### PR DESCRIPTION
**Pull request by mikecroft**
This might be already clarified elsewhere, but this is a useful place to have it.

Signed-off-by: Mike Croft <mike.croft@payara.fish>

### CODE REVIEW

**Comment by johnament** [comment]
@mikecroft do you want to fix the ip check?

**Comment by mikecroft** [comment]
Ah, yeh, I'll make a new pr. I did this change on GitHub so it's got the noreply email in.

**Comment by struberg** [comment]
It's already specified in ConfigSource#getOrdinal() and also in the introduction section afair. So this section is probably redundant then.

**Comment by mikecroft** [comment]
I still think it's useful here @struberg - mostly for people who are just interested in the spec as a user, rather than implementer. The README is often the starting point and it's the text used for the main project page on the microprofile.io website.

**Comment by mikecroft** [comment]
Fixed the IP check @johnament

**Pull request merged**
