### PR TITLE
#386 Adding built-in converters for byte, short and char

### PR DESCRIPTION
**Pull request by gunnarmorling**
As discussed here's a PR for completing the list of built-in converters. Are there other changes needed than that?

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @Emily-Jiang, thanks for reviewing.

>  Can you sign off the PR so that you PR can pass ip-validation

Done.

> Can you add tests to CDIPlainInjectionTest to test the injection of byte, Byte, char, Charater working?

Reworked the last commit for that. Naturally, I haven't actually executed the TCK with these changes yet, as there's no compatible implementation. I'm not sure how you're dealing with this in general, but in the worst case we could adjust later on, should there be a bug in these new tests.

**Comment by gunnarmorling** [comment]
Hey @Emily-Jiang, anything else I should do to get it merged? Thx!

**Comment by struberg** [comment]
Reviewed and applied. Gunnar, you might also add yourself in the NOTICE file if you like.

**Comment by gunnarmorling** [comment]
Thanks! Just checked, I'm listed in the NOTICE file already :)

**Comment by Emily-Jiang** [comment]
@gunnarmorling thanks for your contribution! We will run the tcks against the impls in due course and verify whether they are correct. If not, further issue will be created to correct the tcks. I think some impls have this support already.

**Pull request merged**
