### PR TITLE
[TCK] add test for implicit Enum converter

### PR DESCRIPTION
**Pull request by jmesnil**
Signed-off-by: Jeff Mesnil <jmesnil@gmail.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
@Emily-Jiang a simple test for implicit Enum conversion.

Note that it does not require anything more from the implementation as the Enum implicitely defines the same `valueOf(String)` method than Class: https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html#valueOf(java.lang.Class,%20java.lang.String)

Maybe we should also update the spec and says instead:

> * If the target type `T` is an `Enum`, in which case the `Enum#valueOf(String)` is being used

**Comment by Emily-Jiang** [comment]
@jmesnil your PR failed validation check. Have you assigned ECA and associate your github id with your eclipse account?

**Comment by jmesnil** [comment]
@Emily-Jiang I've amended my commit to use the same email I used for eclipse.org (jmesnil@redhat.com). I'm not sure whether the ip-validation is rechecking but the sign-off is correct now.

**Comment by Emily-Jiang** [comment]
@jmesnil did you sign off ECA? In your eclipse account, you need to put your github id there as well.

**Comment by jmesnil** [comment]
@Emily-Jiang Yes, I've signed off the ECA. I've fixed my local Git repo to use the correct email associated to my eclipse.org and the IP validation works (as in https://github.com/eclipse/microprofile-config/pull/279).
It seems the IP validation is not checking again after I amended the commit. I'll close this PR and open a new one

**Comment by jmesnil** [comment]
superseded by #280

**Pull request closed without merging**
