### PR TITLE
remove @RequestScoped @ConfigProperties bean and the associated test cases

### PR DESCRIPTION
**Pull request by JHahnHRO**
The test cases are fundamentally broken (see issue #762) and cannot possibly work the way they are written.

### CODE REVIEW

**Review by Emily-Jiang — CHANGES_REQUESTED** [review]
The TCK is absolutely fine. Removing the scope support is a big change. What you raised is an implementation issue.

**Comment by Emily-Jiang** [comment]
I am going to close this PR by 5th July if there is no other responses on this PR.

**Comment by Emily-Jiang** [comment]
Close this PR as per my comments above. Please reopen if you still think this should be discussed again.

**Comment by radcortez** [comment]
Yes, I believe that making these beans `@RequestScoped` was a mistake. In most cases, you are not going to observe any changes in the injected values. If we solely consider the specified sources of MP Config, both Env, and Properties are immutable, and System Properties could be changed programmatically (but not really usual). We have to question if this is really useful.

Yes, users could write their own dynamic source and observe new values being loaded on each request, but how many times does that happen on an app lifecycle? Is it worth paying the price for this?

**Pull request closed without merging**
