### PR TITLE
#516 Removed JUnit assertion from test

### PR DESCRIPTION
**Pull request by gpor0**
Escalated from: Using org.junit in TCK tests #516

### CODE REVIEW

**Comment by kenfinnigan** [comment]
From a quick look, it's more than just changing the assert.

@radcortez @Emily-Jiang ??

**Comment by dmlloyd** [comment]
+1 - the change should only address the exact problem.

**Comment by radcortez** [comment]
Hum, some lambdas to method references conversions, removed unused exceptions in the method signatures, and a reorder in the assert parameters. Can't remember exactly the parameter order in TestNG Assert.

Anyway, I would prefer to just see there the Assert fix and have a separate PR to improve code (might be part of a bigger work to do in all classes and not just this one).

**Comment by gpor0** [comment]
Sorry,  IDE reported warnings so i did automatically correct the issues.

**Comment by radcortez** [comment]
It's fine, we can do the warnings on a separate PR.

**Comment by radcortez** [comment]
@gpor0 you will need to sign the Eclipse ECA to be able to contribute. Do you have an Eclipse account?

**Comment by gpor0** [comment]
Yes i have and I did sign the ECA.

**Comment by radcortez** [comment]
Ah it is failing the validation in something else. You need to add the Signed-off-by footer.

Just use ` git commit -a -s` of if you use IntelliJ, there is an option to add it in the commit screen at the top right corner I believe.

Sorry for all this ceremony :(

**Comment by Emily-Jiang** [comment]
@genie-microprofile please test

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by Emily-Jiang** [comment]
This closes #516

**Pull request merged**
