### PR TITLE
Deprecate ConfigProviderResolver.setInstance()

### LINKED ISSUE #364: ConfigProviderResolver#setInstance is an implementation leak and should be dropped from the API
See https://github.com/eclipse/microprofile-open-api/issues/224, this kind of method don't belong to the API and is only issues promises so should disappear from any coming release

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #364

Signed-off-by: David M. Lloyd <david.lloyd@redhat.com>

### CODE REVIEW

**Comment by dmlloyd** [comment]
@Emily-Jiang this should be considered for 1.4.

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by dmlloyd** [comment]
Continuing discussion on the issue (#364)

**Comment by dmlloyd** [comment]
Closing for now.  Will revisit the original use case later.

**Pull request closed without merging**
