### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by LuisGalazM**

### CODE REVIEW

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
Hi @LuisGalazM. Thank you for the PR. To be able to merge it you need go sign the ECA: https://www.eclipse.org/legal/ECA.php.

**Comment by LuisGalazM** [comment]
Hi @radcortez . it's done now.

**Review by Emily-Jiang — APPROVED** [review]
LGTM! Thanks!

**Comment by Emily-Jiang** [comment]
It seems the commit is still not valid due to the following reason.

> Luis Galaz (30141220+LuisGalazM@****.noreply) has a valid Contributor Agreement but it does not cover Eclipse Specification Projects.

Your github email needs to match your ECA sign up email.

**Comment by LuisGalazM** [comment]
@Emily-Jiang it's matches but was private. Now it's public.

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang it's matches but was private. Now it's public.

As you can see from above, there is still a red cross on the ECA. Try to close this one and create another one if you have done  some ECA related changes.

**Pull request closed without merging**
