### PR TITLE
#249 Update bnd file to support CDI 1.1 to 2.x

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@payara.fish>

### CODE REVIEW

**Comment by arjantijms** [comment]
This replaced https://github.com/eclipse/microprofile-config/pull/250

**Comment by Emily-Jiang** [comment]
@arjantijms have you signed ECA?

**Comment by arjantijms** [comment]
@Emily-Jiang 

Payara has, and I'm committing this on behalf of Payara.

**Comment by OndrejM** [comment]
@waynebeaton could you please instruct @arjantijms what to do if he wants to contribute on behalf of Payara. Does he need to sign the ECA too, even if Payara is already a member of the Eclipse foundation and signed the ECA as a company?

**Comment by Emily-Jiang** [comment]
yes, @arjantijms you will need to sign ECA as well. In your eclipse account, you need to put your git id in as well.

**Comment by waynebeaton** [comment]
@Emily-Jiang is right; @arjantijms needs to sign the ECA. There is no notion of a company ECA.

**Comment by arjantijms** [comment]
@Emily-Jiang 
>yes, @arjantijms you will need to sign ECA as well. In your eclipse account, you need to put your git id in as well.

I just signed the ECA, my git id ("arjantijms"), should have been there already. Can the validation be re-executed in this PR, or do I need to create a new PR again, or make a dummy commit?

**Comment by Emily-Jiang** [comment]
@arjantijms you need to create a new PR, I think.

**Comment by arjantijms** [comment]
>@arjantijms you need to create a new PR, I think.

I noticed the checks just passed ;)

**Pull request merged**
